// This file is generated by ./script/discover.js
import { SerializedStyles } from '@emotion/react'
import { sugar } from './main'
import { bg, opacity } from './container/background'
import { rounded, border, outlineNone } from './container/border'
import { boxSizing, box } from './container/boxSizing'
import { fit } from './container/objectFit'
import {
  position,
  relative,
  absolute,
  fixed,
  zIndex,
  left,
  right,
  top,
  bottom,
} from './container/position'
import { shadow, boxShadow } from './container/shadow'
import {
  w,
  h,
  maxW,
  minW,
  maxH,
  minH,
  wFull,
  hFull,
  full,
  square,
} from './container/sizing'
import { animation } from './interactivity/animation'
import { cursor, pointerEvents } from './interactivity/cursor'
import {
  resize,
  overflow,
  overflowX,
  overflowY,
} from './interactivity/overflow'
import {
  transform,
  translate,
  translateX,
  translateY,
} from './interactivity/transform'
import { transition } from './interactivity/transition'
import { select, userSelect } from './interactivity/userSelect'
import {
  row,
  column,
  center,
  flex,
  flexGrow,
  grow,
  flexShrink,
  shrink,
  alignItems,
  alignSelf,
} from './layout'
import {
  m,
  mx,
  my,
  ml,
  mr,
  mt,
  mb,
  p,
  px,
  py,
  pl,
  pr,
  pt,
  pb,
  spaceX,
  spaceY,
} from './layout/spacing'
import {
  color,
  text,
  fontSize,
  fontWeight,
  lineHeight,
  fontSans,
  textShadow,
} from './typography'
import { textEllipsis } from './typography/textEllipsis'
import { when } from './utils'
import { hover, active, focus, disabled, selector } from './utils/selector'

export class Sugar extends Array<SerializedStyles> {
  /** Any SerializedStyles
   * @example
   * sugar(css`object-fit: cover;`)
   * sugar('object-fit: cover')*/
  sugar = sugar

  bg = bg

  opacity = opacity

  rounded = rounded

  border = border

  get outlineNone() {
    return outlineNone.bind(this)()
  }

  boxSizing = boxSizing

  box = box

  fit = fit

  position = position

  get relative() {
    return relative.bind(this)()
  }

  get absolute() {
    return absolute.bind(this)()
  }

  get fixed() {
    return fixed.bind(this)()
  }

  zIndex = zIndex

  left = left

  right = right

  top = top

  bottom = bottom

  shadow = shadow

  boxShadow = boxShadow

  w = w

  h = h

  maxW = maxW

  minW = minW

  maxH = maxH

  minH = minH

  /** set width full */
  get wFull() {
    return wFull.bind(this)()
  }

  /** set height full */
  get hFull() {
    return hFull.bind(this)()
  }

  /** set width and height full */
  get full() {
    return full.bind(this)()
  }

  /** set both width and height
   * ```css
   * {
   *   width: $n;
   *   height: $n;
   * }
   * ``` */
  square = square

  animation = animation

  cursor = cursor

  pointerEvents = pointerEvents

  resize = resize

  overflow = overflow

  overflowX = overflowX

  overflowY = overflowY

  transform = transform

  translate = translate

  translateX = translateX

  translateY = translateY

  transition = transition

  select = select

  userSelect = userSelect

  row = row

  column = column

  get center() {
    return center.bind(this)()
  }

  get flex() {
    return flex.bind(this)()
  }

  flexGrow = flexGrow

  grow = grow

  flexShrink = flexShrink

  shrink = shrink

  /** The CSS align-items property sets the align-self value on all direct children as a group. In Flex box, it controls the alignment of items on the Cross Axis. In Grid Layout, it controls the alignment of items on the Block Axis within their grid area.
   *
   * [MDN Reference](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items)
   */
  alignItems = alignItems

  /**
   * The align-self CSS property overrides a grid or flex item's align-items value. In Grid, it aligns the item inside the grid area. In Flexbox, it aligns the item on the cross axis.
   *
   * [MDN Reference](https://developer.mozilla.org/en-US/docs/Web/CSS/align-self)
   */
  alignSelf = alignSelf

  m = m

  mx = mx

  my = my

  ml = ml

  mr = mr

  mt = mt

  mb = mb

  p = p

  px = px

  py = py

  pl = pl

  pr = pr

  pt = pt

  pb = pb

  spaceX = spaceX

  spaceY = spaceY

  color = color

  text = text

  fontSize = fontSize

  fontWeight = fontWeight

  lineHeight = lineHeight

  get fontSans() {
    return fontSans.bind(this)()
  }

  textShadow = textShadow

  /** 文本溢出省略 */
  textEllipsis = textEllipsis

  when = when

  hover = hover

  active = active

  focus = focus

  disabled = disabled

  selector = selector
}

export {
  sugar,
  bg,
  opacity,
  rounded,
  border,
  outlineNone,
  boxSizing,
  box,
  fit,
  position,
  relative,
  absolute,
  fixed,
  zIndex,
  left,
  right,
  top,
  bottom,
  shadow,
  boxShadow,
  w,
  h,
  maxW,
  minW,
  maxH,
  minH,
  wFull,
  hFull,
  full,
  square,
  animation,
  cursor,
  pointerEvents,
  resize,
  overflow,
  overflowX,
  overflowY,
  transform,
  translate,
  translateX,
  translateY,
  transition,
  select,
  userSelect,
  row,
  column,
  center,
  flex,
  flexGrow,
  grow,
  flexShrink,
  shrink,
  alignItems,
  alignSelf,
  m,
  mx,
  my,
  ml,
  mr,
  mt,
  mb,
  p,
  px,
  py,
  pl,
  pr,
  pt,
  pb,
  spaceX,
  spaceY,
  color,
  text,
  fontSize,
  fontWeight,
  lineHeight,
  fontSans,
  textShadow,
  textEllipsis,
  when,
  hover,
  active,
  focus,
  disabled,
  selector,
}

export * from './helper'

export * from './main'
